# Generated by Django 6.0.6 on 2026-06-15 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('account_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('balance', models.FloatField(default=0)),
                ('account_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('user_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=100)),
                ('is_admin', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('amount', models.FloatField(default=0)),
                ('transation_date', models.FloatField(default=0)),
                ('transaction_type', models.CharField(default='', max_length=200)),
                ('receiver_account_id', models.CharField(default='', max_length=10)),
                ('sender_account_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='database.bankaccount')),
            ],
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='database.userprofile'),
        ),
    ]
